### ISSUE TITLE
version-script snap command is deprecated: Use snapcraftctl set-version part scriptlet instead.

### ISSUE THREAD

**Issue by davdunc** [davdunc/aws-cli-snap#4]
version: git
version-script: cat $SNAPCRAFT_STAGE/version 

needs to be modified to continue deployment. 

My challenge is keeping the awsv2 distinct from aws cli commands

**Comment by rcj4747** [comment]
I ran a snapcraft build from `master` and it built `aws-cli_1.18.17_amd64.snap` but from the branch `issue-4` it built `aws-cli_0+git.824cacd_amd64.snap`.  So I wanted to find out what the version was describing.  A `git show 824cacd` in the aws-cli repo returns no results but run in aws-cli-snap's repo it shows me the commit at the head of the issue-4 branch.  So this now appears to be getting the tag from this repo instead of the aws-cli repo.

I see in the snapcraft output "Determining the version from the project repo (version: git)." so I wonder if removing version-script from the top level of the yaml for the snap is hitting fallback behavior and the `snapcraftctl set-version $TAG` down in the aws part isn't propagating up.

**Comment by rcj4747** [comment]
In summary, you'd like to remove 'version-script' and use scriptlet to set the version but you're not seeing the same behavior after the change as documented in my comment above.

**Comment by rcj4747** [comment]
Per [a comment by popey](https://forum.snapcraft.io/t/git-error-while-building-snap/10130/2) the `version: git` only works if the snapcraft.yaml is in the same repo.  He suggests using [adopt-info](https://snapcraft.io/docs/using-external-metadata) and that worked for me.  With this patch it builds aws-cli_1.18.17_amd64.snap today.

```
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index ec1a087..fb28ded 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -3,8 +3,8 @@ summary: Universal Command Line Interface for Amazon Web Services
 description: |
  This package provides a unified command line interface to Amazon Web
  Services.
-version: git
 base: core18
+adopt-info: aws
 
 confinement: strict
 grade: stable
```

**Comment by davdunc** [comment]
awesome. That's exactly what was required.
